### ISSUE TITLE
Merge single-line diagram and network-area diagram viewers

### ISSUE THREAD

**Issue by So-Fras** [powsybl/powsybl-dev-tools#77]
* **Do you want to request a *feature* or report a *bug*?**
Feature

* **What is the current behavior?**
Two separate viewers for single-line diagrams and network-area diagrams.

* **What is the expected behavior?**
One single viewer with 2 tabs for single-line diagrams and network-area diagrams. 
The common panels (to load the network and navigate through it) are materialized by yellow rectangles on the picture below. The purple rectangle at the center represents the spot for the 2 different tabs. 
Any element that is specific to one of the diagrams should be moved to the appropriate tab. An example is given on the picture below with the depth parameter (linked with network-area diagrams only).
![joinedViewer](https://user-images.githubusercontent.com/93923177/219352153-1365fc25-caa1-4f68-88ae-b4419e7ddc6b.png)

* **What is the motivation / use case for changing the behavior?**
Avoid code duplication

**Comment by So-Fras** [comment]
There is also a need to clean the single-line diagram part before or after merging the viewers: see in particular commit 03e14572a3efdae5cfce6cca2ef43e0592fff8ec
Some deletions may have been "harmful".

**Comment by tadam50** [comment]
> There is also a need to clean the single-line diagram part before or after merging the viewers: see in particular commit [03e1457](https://github.com/powsybl/powsybl-dev-tools/commit/03e14572a3efdae5cfce6cca2ef43e0592fff8ec) Some deletions may have been "harmful".

Fixed by: https://github.com/powsybl/powsybl-dev-tools/pull/78
